package com.myteam.oopath;

// traditional 

rule "Find my grandchildren"
when
	$p:Person()
	$child: Person() from $p.getChildren()
	$grandChild: Person() from $child.getChildren()
then
	System.out.println($grandChild.getName() + " is a grandchild of " + $p.getName());
end


// oopath way
/*
rule "Find my grandchildren"
when
	//Implement the rule above with an OOPath oneliner.
	$p: Person($grandChild: /children/children)
then
	System.out.println("OOPath: " + $grandChild.getName() + " is a grandchild of " + $p.getName());
end
*/