package com.myteam.oopath;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Age")
	private int age;
	@org.kie.api.definition.type.Label(value = "Children")
	private java.util.List<com.myteam.oopath.Person> children;

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.util.List<com.myteam.oopath.Person> getChildren() {
		return this.children;
	}

	public void setChildren(java.util.List<com.myteam.oopath.Person> children) {
		this.children = children;
	}

	public Person(java.lang.String name, int age,
			java.util.List<com.myteam.oopath.Person> children) {
		this.name = name;
		this.age = age;
		this.children = children;
	}
	
	// hand-crafted below
		public Person(java.lang.String name, int age ) {
		this.name = name;
		this.age = age;
	}
	
	public void addChild(Person child) {
		children.add(child);
	}

}